// <auto-generated />
using System;
using FCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCanteen.Data.Migrations
{
    [DbContext(typeof(FCanteenContext))]
    partial class FCanteenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MON01",
                            IsAvailable = true,
                            Name = "Cơm tấm sườn",
                            Price = 35000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MON02",
                            IsAvailable = true,
                            Name = "Cơm gà xối mỡ",
                            Price = 32000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MON03",
                            IsAvailable = true,
                            Name = "Bún bò Huế",
                            Price = 30000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MON04",
                            IsAvailable = true,
                            Name = "Bún chả cá",
                            Price = 28000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 5,
                            Code = "MON05",
                            IsAvailable = true,
                            Name = "Phở bò",
                            Price = 33000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 6,
                            Code = "MON06",
                            IsAvailable = true,
                            Name = "Mì Quảng",
                            Price = 29000m,
                            Unit = "tô"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MON07",
                            IsAvailable = true,
                            Name = "Bánh mì thịt",
                            Price = 18000m,
                            Unit = "ổ"
                        },
                        new
                        {
                            Id = 8,
                            Code = "MON08",
                            IsAvailable = true,
                            Name = "Bánh xèo",
                            Price = 25000m,
                            Unit = "cái"
                        },
                        new
                        {
                            Id = 9,
                            Code = "MON09",
                            IsAvailable = true,
                            Name = "Cơm chiên dương châu",
                            Price = 27000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 10,
                            Code = "MON10",
                            IsAvailable = true,
                            Name = "Mì xào bò",
                            Price = 30000m,
                            Unit = "phần"
                        },
                        new
                        {
                            Id = 11,
                            Code = "MON11",
                            IsAvailable = true,
                            Name = "Trà đá",
                            Price = 3000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 12,
                            Code = "MON12",
                            IsAvailable = true,
                            Name = "Trà chanh",
                            Price = 10000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 13,
                            Code = "MON13",
                            IsAvailable = true,
                            Name = "Nước cam ép",
                            Price = 15000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 14,
                            Code = "MON14",
                            IsAvailable = true,
                            Name = "Sinh tố bơ",
                            Price = 20000m,
                            Unit = "ly"
                        },
                        new
                        {
                            Id = 15,
                            Code = "MON15",
                            IsAvailable = true,
                            Name = "Cà phê sữa đá",
                            Price = 15000m,
                            Unit = "ly"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CounterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("TicketLines")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Navigation("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
